spring.application.name=convergence

# Postgres
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.wmltiuocgcvfyhxloxwq&password=dXqaAK8VOcNfPo3u
spring.datasource.username=postgres.wmltiuocgcvfyhxloxwq
spring.datasource.password=dXqaAK8VOcNfPo3u
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# JWT
jwt.secret=abracadabrahahaha
jwt.expiration=86400000

# Scheduling
spring.task.scheduling.pool.size=4

# Redis (disable auto-config if not using Redis yet)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# RabbitMQ (disable auto-config if not using RabbitMQ yet)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.auto-startup=false