spring.application.name=convergence

# Postgres
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.wmltiuocgcvfyhxloxwq&password=dXqaAK8VOcNfPo3u
spring.datasource.username=postgres.wmltiuocgcvfyhxloxwq
spring.datasource.password=dXqaAK8VOcNfPo3u
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.subham.convergence=DEBUG

# JWT
jwt.secret=convergence-super-secret-key-for-jwt-signing-2026-abcdefgh
jwt.expiration=86400000

# Scheduling
spring.task.scheduling.pool.size=4

# Redis (disable auto-config if not using Redis yet)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# RabbitMQ (disable auto-config if not using RabbitMQ yet)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.auto-startup=false

logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Set max-lifetime to be 30-60 seconds shorter than the DB's wait_timeout
# 10 minutes (600000ms) is a safe starting point for most local/cloud setups
spring.datasource.hikari.max-lifetime=600000

# Reduces the time Hikari waits for a connection before throwing an error
spring.datasource.hikari.connection-timeout=20000

# Keeps connections alive by sending a "heartbeat" query
spring.datasource.hikari.keepalive-time=30000

reddit.url = ${REDDIT_URL: https://www.reddit.com/user/the_now_2003/saved.json?feed=6b69a31def6e7bc2a035ec833a4f4a59d92d525c&user=the_now_2003}

